# Generated by Django 5.2.11 on 2026-02-04 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("desired_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("app_id", models.BigIntegerField(blank=True, null=True)),
                ("slug", models.CharField(blank=True, max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("private_key_pem", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("zai", "ZAI / GLM")], max_length=32),
                ),
                ("api_key", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="githubinstallation",
            name="installation_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="githubrepository",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="githubrepository",
            name="repo_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="githubrepository",
            constraint=models.UniqueConstraint(
                fields=("installation", "repo_id"), name="github_repo_per_installation"
            ),
        ),
        migrations.AddField(
            model_name="githubapp",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="github_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="github_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="web.githubapp",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.UniqueConstraint(
                fields=("github_app", "installation_id"),
                name="github_installation_per_app",
            ),
        ),
        migrations.AddField(
            model_name="userapikey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userapikey",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="api_key_per_user_provider"
            ),
        ),
    ]
