# Generated by Django 5.2.11 on 2026-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_ruleset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
