# Generated by Django 5.2.11 on 2026-02-05 00:00

from __future__ import annotations

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_chatmessage_hidden_at_chatmessage_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrun",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="reviewrun",
            index=models.Index(
                fields=["status", "-created_at"], name="reviewrun_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewrun",
            index=models.Index(
                fields=["pull_request", "-created_at"], name="reviewrun_pr_created_idx"
            ),
        ),
    ]
