# Generated by Django 5.2.11 on 2026-02-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_reviewrun_timestamps_and_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewrun',
            name='reviewrun_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewrun',
            name='reviewrun_pr_created_idx',
        ),
    ]
